### ISSUE TITLE
Only Data signal off, not Power in RaspberryPi3 port 3, 4, 5

### ISSUE THREAD

**Issue by bookledge** [codazoda/hub-ctrl.c#11]
When I use this command, it works

  sudo ./hub-ctrl -h 0 -P 2 -p 0 ; sleep 3; sudo ./hub-ctrl  -h 0 -P 2 -p 1

All usb ports are powered off. 

but, I want to control individual ports. 

So I command this line to my raspberry pi in order to reset the power of USB port 4

  sudo ./hub-ctrl -h 0 -P 4 -p 0 ; sleep 3; sudo ./hub-ctrl  -h 0 -P 4 -p 1

It seams like works, but actually it doesn't.

I noticed the Signal has been off, but Power is not. 

How can I solve this problem.

**Comment by majuss** [comment]
I would also be interested in the control of individual ports. I'am experimenting with it, but results are like yours, not useful at all.

It seems like we can't control individual ports, because of the wiring of the Pi's hub.

**Comment by Tsjippy** [comment]
same problem here

**Comment by EvansJahja** [comment]
Seems like this is a hardware limitation.
