### ISSUE TITLE
Problems switching power with RaspberryPi 3 Model B+

### ISSUE THREAD

**Issue by armrasp** [codazoda/hub-ctrl.c#13]
Hi there, 
actually using this tool to switch power of the internal hub at the Raspi 3 Mod B (no plus). No problem, perfect, thanks a lot.
(switches VID:PID 0424:9514)

Yesterday I adapted my application-code to support the Raspi 3 Mod B+ as well (VID:PID 0424:2514, the 2nd hub detected). What I observed is that the Raspberry's hub is automatically re-powered after approx. 7 seconds, after I switched off the hub.

Even if only related. this is probably not an issue of this tool, even more likely a new 'feature of the new kernel/firmware/module of the current Raspbian. But where and why?

Can somebody help me please, to keep the RPI-hub switched off? I do not know where to dig deeper for this issue.

**Comment by leperjulien** [comment]
https://github.com/mvp/uhubctl/issues/96

**Comment by lkord** [comment]
try hub=1

      sudo hub-ctrl.c/hub-ctrl -h 1 -P 2  -p 0

**Comment by srijansaxena11** [comment]
hub=1 works... thanks :)
