### ISSUE TITLE
Raspberry Pi 4 Compatible?

### ISSUE THREAD

**Issue by ikarofsouza** [codazoda/hub-ctrl.c#17]
Hello good day. Would you like to request information if the code is compatible with Raspberry Pi 4 4GB?

**Comment by srijansaxena11** [comment]
doesnt seem to. well it seems like rbpi4 issue but i'm unable to control the usb ports power.

**Comment by oligu** [comment]
Works fine for me, at least on one port (bottom left). Haven't tested the other ports.
`sudo ./hub-ctrl -h 3 -P 1 -p 0`

**Comment by Tsjippy** [comment]
Doesn't work for me on a RPI4 4GB

**Comment by codazoda** [comment]
Some RPI4 users report it works, some report it doesn't. I don't have my own the hardware to test this so I'm going to close this issue for now.

**Comment by Sodium-Hydrogen** [comment]
I've been testing this functionality and it looks like `/sys/bus/usb/devices/1-1/bConfigurationValue` is important for my installation. Writing a 0 to this and triggering `hub-ctrl` to turn off the port works. It doesn't seem to work without writing to that file. Writing a 1 allows hub-ctrl to turn it back on.

_[Source thread for control file](https://www.raspberrypi.org/forums/viewtopic.php?t=246851)_
