### ISSUE TITLE
failed to control

### ISSUE THREAD

**Issue by TylonHH** [codazoda/hub-ctrl.c#6]
Hi,
how can I investigate the
``failed to control.``
``: Invalid argument``
error?
I get this when I try on my Pi3 ``sudo ./hub-ctrl -h 0 -P 2 -p 1 ``

best regards

EDIT
pi@octopi:~ $ sudo ./hub-ctrl -v
Hub #0 at 001:001
 INFO: ganged switching.
 WARN: Port indicators are NOT supported.
 Hub Port Status:
   Port 1: 0000.0000

**Comment by pippopippo69** [comment]
Hi

I am trying to find the right paramenters to switch off and then on again all usb ports of my Raspberry Pi 3 ...

any hint?

tks

**Comment by TylonHH** [comment]
I don't know why, but
´´sudo ./hub-ctrl -h 0 -P 2 -p 1´´
is working for me. I have an USB Webcam wich I can know switch off and off.

In an [other blog](http://embeddedapocalypse.blogspot.de/2016/10/how-to-power-off-raspberry-pi-3-usb-or.html?showComment=1494071204938#c3464904721488963239), there was
´sudo ./hub-ctrl.c -h 0 -P 2 -p 1´´
sugested. But didn't work for me.

**Comment by sabag** [comment]
for me at first it also did not work, but when i inspected the output of "lsusb -t" i changed the command to hub 1 and it worked:
sudo ./hub-ctrl -h 1 -P 2 -p 1

(btw i have RPi 3B+)

**Comment by codazoda** [comment]
There are several other issues here that mention the Pi 3 and settings that seem to work. I have no experience with it myself but it might be worth a shot to try the solutions mentioned above and solutions found in other closed issues here.
