### ISSUE TITLE
DLINK DUB-H7 Ver C1 no power control.

### ISSUE THREAD

**Issue by k1tzu** [codazoda/hub-ctrl.c#7]
If you plug a device, for example, in the first port of the hub from the left
and execute ./hub-ctrl -h 3 -P 4 -p0
then it will just reconnect the device in that port, it doesn't shut the port power off
So I spent 35$ in vain.
Please remove this hub from the readme.

There's a newer version of the hub - D1. Maybe it works?

**Comment by codazoda** [comment]
I added a note to the readme indicating that the C1 didn't work for this user.
