### ISSUE TITLE
Error in the Compilng step

### ISSUE THREAD

**Issue by Gerri1989** [codazoda/hub-ctrl.c#9]
When I try to do the Compiling there's an error: 

gcc: error: hub-ctrl.c: The file or the directory doesn't exist

Somebody can help me pls?

PS: I'm working on a Raspberry Pi 2

**Comment by compute-e** [comment]
You need to download the _hub-ctrl.c_ file first _(from this repository)_, save it somewhere  
on your RPi and run that command in the folder / directory it's stored in.

@codazoda this issue can be closed, I think the problem is fixed.
